### ISSUE TITLE
Create Core Team View

### ISSUE THREAD

**Issue by adamstacey7** [adamstacey7/bp-two-team#9]
Display a list of thumbnails of each team member:

- Profile img
- Fullname
- Role

Wirefames:

https://trello-attachments.s3.amazonaws.com/5a817e4cc9374e4e63b48d5f/5a817e4cc9374e4e63b48d8e/c9372ed064c57886cfbe55ee2b66035d/Idean_-_CVs_-_Centrica_team2.pdf

**Comment by afreeman123** [comment]
#34
